-- 05: Reshape applicants table to match Django AbituriyentProfile
-- - drop dictionary FKs (region/district/nationality/citizenship)
-- - rename middle_name → other_name
-- - add passport_series, pinfl, image_id, passport_file_id, nationality (string)
-- - re-point region/district FKs to new regions/districts tables
BEGIN;

-- Drop FK constraints to dictionary_items first (names auto-generated by Alembic naming convention)
ALTER TABLE applicants DROP CONSTRAINT IF EXISTS fk_applicants_region_id_dictionary_items;
ALTER TABLE applicants DROP CONSTRAINT IF EXISTS fk_applicants_district_id_dictionary_items;
ALTER TABLE applicants DROP CONSTRAINT IF EXISTS fk_applicants_nationality_id_dictionary_items;
ALTER TABLE applicants DROP CONSTRAINT IF EXISTS fk_applicants_citizenship_id_dictionary_items;

-- Drop the old columns we don't need anymore
ALTER TABLE applicants DROP COLUMN IF EXISTS nationality_id;
ALTER TABLE applicants DROP COLUMN IF EXISTS citizenship_id;
ALTER TABLE applicants DROP COLUMN IF EXISTS profile_photo_id;

-- Rename middle_name → other_name
ALTER TABLE applicants RENAME COLUMN middle_name TO other_name;

-- Add new fields
ALTER TABLE applicants
    ADD COLUMN IF NOT EXISTS passport_series VARCHAR(9),
    ADD COLUMN IF NOT EXISTS pinfl VARCHAR(14),
    ADD COLUMN IF NOT EXISTS nationality VARCHAR(50) NOT NULL DEFAULT 'O''zbek',
    ADD COLUMN IF NOT EXISTS image_id UUID REFERENCES files(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS passport_file_id UUID REFERENCES files(id) ON DELETE SET NULL;

-- Existing region_id / district_id columns: were UUID FK to dictionary_items.
-- Reset to NULL (data could not be migrated cleanly from dictionary names) and
-- re-point FKs to new regions/districts tables.
UPDATE applicants SET region_id = NULL, district_id = NULL;

ALTER TABLE applicants
    ADD CONSTRAINT fk_applicants_region_id_regions
        FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_applicants_district_id_districts
        FOREIGN KEY (district_id) REFERENCES districts(id) ON DELETE SET NULL;

-- Uniqueness on passport_series and pinfl (NULL allowed)
CREATE UNIQUE INDEX IF NOT EXISTS uq_applicants_passport_series ON applicants(passport_series) WHERE passport_series IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_applicants_pinfl ON applicants(pinfl) WHERE pinfl IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_applicants_passport_series ON applicants(passport_series);
CREATE INDEX IF NOT EXISTS ix_applicants_pinfl ON applicants(pinfl);

-- Drop legacy passports + educations tables (folded into applicants + diploms)
DROP TABLE IF EXISTS passports CASCADE;
DROP TABLE IF EXISTS educations CASCADE;

COMMIT;
